name: mobile_app_final
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  carousel_slider:
  email_validator: "^2.1.17"
  intl: ^0.18.0
  firebase_auth: ^5.3.3
  badges: ^3.0.2
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
